### ISSUE TITLE
Run command example for docker

### ISSUE THREAD

**Issue by adrianog** [paulfantom/dockerfiles#5]
Thanks for the containers. Could you possibly provide an example of how to run them? That'd be much appreciated.

**Comment by paulfantom** [comment]
There are no plans for documenting every container image created in this repository.

If you need help with a specific image, please tell me which one.

**Comment by adrianog** [comment]
Thanks, I'm using [aheimsbakk/systemd-ubuntu](https://github.com/aheimsbakk/systemd-ubuntu) :
```docker run -d -t --name "mydocker" --hostname "mydocker" --shm-size=22g --privileged  -e APT=iproute2,procps,iputils-ping,dnsutils,traceroute --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro aheimsbakk/systemd-ubuntu:18.04```

**Comment by paulfantom** [comment]
All systemd images are meant only as a base to test ansible roles using molecule framework (as stated in [readme]( https://github.com/paulfantom/dockerfiles/tree/master/systemd)). Any other usage is our of scope.

Usage can be found in @cloudalchemy ansible roles, ex. https://github.com/cloudalchemy/ansible-node-exporter/blob/master/molecule/alternative/molecule.yml
